"""Local SQLite persistence for Iapetus (kernel DB core + domain repositories)."""
from __future__ import annotations

from iapetus.database.core import (
    KERNEL_DB_FILENAME,
    KERNEL_SCHEMA_VERSION,
    KernelDatabase,
    LEARNING_INDEX_DB_FILENAME,
    SCHEMA_VERSION,
    apply_kernel_schema,
    apply_schema,
    apply_schema_meta,
    connect_learning_index,
    default_kernel_database,
    default_kernel_db_path,
    default_learning_index_db_path,
    init_kernel_database,
    init_learning_index_database,
    kernel_connection,
    kernel_database_health,
    learning_index_connection,
    open_connection,
    read_schema_version,
    write_schema_version,
)
from iapetus.database.repositories import (
    LearningRunRepository,
    default_learning_run_repository,
    extract_run_index_row,
    index_learning_runs,
    learning_index_status,
    list_indexed_runs,
    metrics_for_run_id,
    register_learning_run,
)

__all__ = [
    "KERNEL_DB_FILENAME",
    "KERNEL_SCHEMA_VERSION",
    "KernelDatabase",
    "LEARNING_INDEX_DB_FILENAME",
    "LearningRunRepository",
    "SCHEMA_VERSION",
    "apply_kernel_schema",
    "apply_schema",
    "apply_schema_meta",
    "connect_learning_index",
    "default_kernel_database",
    "default_kernel_db_path",
    "default_learning_index_db_path",
    "default_learning_run_repository",
    "extract_run_index_row",
    "index_learning_runs",
    "init_kernel_database",
    "init_learning_index_database",
    "kernel_connection",
    "kernel_database_health",
    "learning_index_connection",
    "learning_index_status",
    "list_indexed_runs",
    "metrics_for_run_id",
    "open_connection",
    "read_schema_version",
    "register_learning_run",
    "write_schema_version",
]
