"""Central contract names and versions for persisted Iapetus artifacts."""
from __future__ import annotations

from iapetus.contracts.learning import (
    LEARNING_ARTIFACT_MANIFEST_SCHEMA_NAME,
    LEARNING_ARTIFACT_MANIFEST_SCHEMA_VERSION,
    LEARNING_RUN_MANIFEST_SCHEMA_NAME,
    LEARNING_RUN_MANIFEST_SCHEMA_VERSION,
    LEARNING_RUN_RESULT_SCHEMA_NAME,
    LEARNING_RUN_RESULT_SCHEMA_VERSION,
    SNAPSHOT_MANIFEST_SCHEMA_NAME,
    SNAPSHOT_MANIFEST_SCHEMA_VERSION,
    STATIC_MLP_V2_MODE,
    normalize_learning_mode_alias,
)

__all__ = [
    "LEARNING_ARTIFACT_MANIFEST_SCHEMA_NAME",
    "LEARNING_ARTIFACT_MANIFEST_SCHEMA_VERSION",
    "LEARNING_RUN_MANIFEST_SCHEMA_NAME",
    "LEARNING_RUN_MANIFEST_SCHEMA_VERSION",
    "LEARNING_RUN_RESULT_SCHEMA_NAME",
    "LEARNING_RUN_RESULT_SCHEMA_VERSION",
    "SNAPSHOT_MANIFEST_SCHEMA_NAME",
    "SNAPSHOT_MANIFEST_SCHEMA_VERSION",
    "STATIC_MLP_V2_MODE",
    "normalize_learning_mode_alias",
]
