"""Backward-compatible re-exports for ``iapetus.data`` (prefer ``iapetus.data`` in new code)."""
from __future__ import annotations

from iapetus.data import (
    CURATED_DIR,
    DATA_DIR,
    FIXTURE_COOCCURRENCE_PATH,
    FIXTURE_SEED_PATH,
    GENERATED_DIR,
    KNOWLEDGE_SUMMARY_PATH,
    MANIFESTS_DIR,
    PERMISSIONS_SEED_PATH,
    RAW_DIR,
    REFERENCE_RAW_DIR,
    SOURCE_MANIFEST_PATH,
    STATIC_TOKEN_SEED_PATH,
    TOKEN_VOCABULARY_PATH,
    TRAINING_CORPUS_PATH,
    SeedFixtureSample,
    SourceManifest,
    TrustedLevel,
    build_feature_vocabulary,
    build_token_summary,
    download_reference_sources,
    fixture_seed_as_labels,
    list_source_manifests,
    load_fixture_seed,
    load_permission_seed,
    load_static_token_seed,
    seed_summary,
    validate_seed_payloads,
)

__all__ = [
    "DATA_DIR",
    "CURATED_DIR",
    "RAW_DIR",
    "GENERATED_DIR",
    "KNOWLEDGE_SUMMARY_PATH",
    "TOKEN_VOCABULARY_PATH",
    "FIXTURE_COOCCURRENCE_PATH",
    "TRAINING_CORPUS_PATH",
    "MANIFESTS_DIR",
    "REFERENCE_RAW_DIR",
    "SOURCE_MANIFEST_PATH",
    "PERMISSIONS_SEED_PATH",
    "STATIC_TOKEN_SEED_PATH",
    "FIXTURE_SEED_PATH",
    "SeedFixtureSample",
    "SourceManifest",
    "TrustedLevel",
    "build_feature_vocabulary",
    "build_token_summary",
    "download_reference_sources",
    "fixture_seed_as_labels",
    "list_source_manifests",
    "load_fixture_seed",
    "load_permission_seed",
    "load_static_token_seed",
    "seed_summary",
    "validate_seed_payloads",
]
